In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv('insurance_data.csv')
data

age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [3]:
x = data.iloc[:,:-1].values
x


array([[22],
       [25],
       [47],
       [52],
       [46],
       [56],
       [55],
       [60],
       [62],
       [61],
       [18],
       [28],
       [27],
       [29],
       [49],
       [55],
       [25],
       [58],
       [19],
       [18],
       [21],
       [26],
       [40],
       [45],
       [50],
       [54],
       [23]], dtype=int64)

In [4]:
y = data.iloc[:, -1].values
y

array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 0], dtype=int64)

In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)


In [6]:
x_test

array([[58],
       [49],
       [19],
       [52],
       [45],
       [18]], dtype=int64)

In [7]:
x_train

array([[21],
       [26],
       [46],
       [47],
       [40],
       [55],
       [18],
       [29],
       [60],
       [50],
       [25],
       [25],
       [22],
       [55],
       [23],
       [54],
       [61],
       [62],
       [27],
       [28],
       [56]], dtype=int64)

In [8]:
y_test

array([1, 1, 0, 0, 1, 0], dtype=int64)

In [9]:
y_train

array([0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1],
      dtype=int64)

In [10]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=1)
classifier.fit(x_train,y_train)


LogisticRegression(random_state=1)

In [11]:
ypred=classifier.predict(x_test)
ypred

array([1, 1, 0, 1, 1, 0], dtype=int64)

In [12]:
classifier.score(x_test,y_test)

0.8333333333333334

In [13]:
classifier.predict_proba(x_test)

array([[0.04795632, 0.95204368],
       [0.15805894, 0.84194106],
       [0.93776133, 0.06223867],
       [0.10800643, 0.89199357],
       [0.25198743, 0.74801257],
       [0.94576637, 0.05423363]])

In [14]:
classifier.predict([[52]])

array([1], dtype=int64)

In [15]:
classifier.predict([[24]])

array([0], dtype=int64)